import { Job } from '@/types';

export const mockJobs: Job[] = [
  {
    id: 'mock-1',
    title: 'Senior Product Manager, AI Platform',
    company: 'Google',
    companyLogo: 'https://logo.clearbit.com/google.com',
    industry: 'Information Technology',
    location: 'Mountain View, CA',
    workModel: 'hybrid',
    jobType: 'fulltime',
    experienceLevel: 'senior',
    experienceYears: '5-8 years',
    salaryMin: 185000,
    salaryMax: 280000,
    description:
      'Lead product strategy for our AI/ML platform powering Google Cloud services. Partner with engineering and design to define the roadmap for developer-facing AI tools, evaluate market opportunities, and drive adoption across enterprise customers.',
    applyUrl: 'https://www.google.com/about/careers/applications/jobs/results/12345678901234567890',
    companyPortalUrl: 'https://careers.google.com',
    postedAt: '3 hours ago',
    applicantCount: 47,
    h1bSponsorship: true,
    socialProof: '2 school alumni work here',
    matchScore: 94,
    atsType: 'google',
  },
  {
    id: 'mock-2',
    title: 'Software Engineer, Infrastructure',
    company: 'Meta',
    companyLogo: 'https://logo.clearbit.com/meta.com',
    industry: 'Information Technology',
    location: 'Menlo Park, CA',
    workModel: 'hybrid',
    jobType: 'fulltime',
    experienceLevel: 'mid',
    experienceYears: '3-5 years',
    salaryMin: 170000,
    salaryMax: 250000,
    description:
      'Build and scale the infrastructure that powers Meta\'s family of apps. Work on distributed systems, storage, and compute platforms serving billions of users globally. Strong focus on reliability, performance, and efficiency.',
    applyUrl: 'https://www.metacareers.com/jobs/987654321098765/',
    companyPortalUrl: 'https://www.metacareers.com',
    postedAt: '5 hours ago',
    applicantCount: 132,
    h1bSponsorship: true,
    socialProof: '1 former colleague works here',
    matchScore: 88,
    atsType: 'custom',
  },
  {
    id: 'mock-3',
    title: 'Staff Software Engineer, Payments',
    company: 'Stripe',
    companyLogo: 'https://logo.clearbit.com/stripe.com',
    industry: 'Finance',
    location: 'San Francisco, CA',
    workModel: 'hybrid',
    jobType: 'fulltime',
    experienceLevel: 'lead',
    experienceYears: '8+ years',
    salaryMin: 220000,
    salaryMax: 350000,
    description:
      'Design and implement core payment processing systems at massive scale. Lead technical initiatives to improve payment authorization rates, reduce latency, and expand Stripe\'s global payment capabilities. Mentor senior engineers across the organization.',
    applyUrl: 'https://stripe.com/jobs/listing/staff-software-engineer-payments/5432109',
    companyPortalUrl: 'https://stripe.com/jobs',
    postedAt: '1 day ago',
    applicantCount: 89,
    h1bSponsorship: true,
    socialProof: '3 school alumni work here',
    matchScore: 82,
    atsType: 'greenhouse',
  },
  {
    id: 'mock-4',
    title: 'Data Scientist, Pricing & Revenue',
    company: 'Airbnb',
    companyLogo: 'https://logo.clearbit.com/airbnb.com',
    industry: 'E-Commerce',
    location: 'San Francisco, CA',
    workModel: 'remote',
    jobType: 'fulltime',
    experienceLevel: 'mid',
    experienceYears: '3-5 years',
    salaryMin: 150000,
    salaryMax: 220000,
    description:
      'Apply statistical modeling and machine learning to optimize Airbnb\'s dynamic pricing algorithms. Analyze host and guest behavior to identify revenue opportunities, run A/B experiments, and present insights to leadership.',
    applyUrl: 'https://careers.airbnb.com/positions/5678901/',
    companyPortalUrl: 'https://careers.airbnb.com',
    postedAt: '2 hours ago',
    applicantCount: 23,
    h1bSponsorship: true,
    socialProof: 'Be an early applicant',
    matchScore: 91,
    atsType: 'greenhouse',
  },
  {
    id: 'mock-5',
    title: 'Senior Software Engineer, Database Internals',
    company: 'MongoDB',
    companyLogo: 'https://logo.clearbit.com/mongodb.com',
    industry: 'Software',
    location: 'New York, NY',
    workModel: 'hybrid',
    jobType: 'fulltime',
    experienceLevel: 'senior',
    experienceYears: '5-8 years',
    salaryMin: 160000,
    salaryMax: 240000,
    description:
      'Work on the core storage engine and query execution layer of MongoDB. Optimize performance for high-throughput workloads, implement new query operators, and contribute to the distributed consensus protocol.',
    applyUrl: 'https://app.greenhouse.io/boards/mongodb/jobs/7654321',
    companyPortalUrl: 'https://www.mongodb.com/careers',
    postedAt: '6 hours ago',
    applicantCount: 56,
    h1bSponsorship: true,
    socialProof: '1 school alumni works here',
    matchScore: 85,
    atsType: 'greenhouse',
  },
  {
    id: 'mock-6',
    title: 'Embedded Software Engineer',
    company: 'LG Electronics',
    companyLogo: 'https://logo.clearbit.com/lg.com',
    industry: 'Manufacturing',
    location: 'Santa Clara, CA',
    workModel: 'onsite',
    jobType: 'fulltime',
    experienceLevel: 'mid',
    experienceYears: '3-6 years',
    salaryMin: 120000,
    salaryMax: 175000,
    description:
      'Develop embedded software for next-generation smart home and entertainment devices. Work with firmware, RTOS, and Linux-based systems. Collaborate with hardware teams to bring new consumer electronics products to market.',
    applyUrl: 'https://careers.lg.com/job/embedded-software-engineer/J3N2FZ6XJZ4MHBK1QGR',
    companyPortalUrl: 'https://careers.lg.com',
    postedAt: '1 day ago',
    applicantCount: 34,
    h1bSponsorship: true,
    socialProof: '2 former colleagues work here',
    matchScore: 67,
    atsType: 'workday',
  },
  {
    id: 'mock-7',
    title: 'Robotics Software Engineer',
    company: 'Globus Medical',
    companyLogo: 'https://logo.clearbit.com/globusmedical.com',
    industry: 'Healthcare',
    location: 'Audubon, PA',
    workModel: 'onsite',
    jobType: 'fulltime',
    experienceLevel: 'senior',
    experienceYears: '5-7 years',
    salaryMin: 140000,
    salaryMax: 200000,
    description:
      'Design and implement real-time control software for surgical robotic systems. Develop motion planning algorithms, integrate sensor feedback loops, and ensure FDA-compliant software development lifecycle practices.',
    applyUrl: 'https://globusmedical.wd5.myworkdayjobs.com/en-US/careers/job/Audubon-PA/Robotics-Software-Engineer_JR1024',
    companyPortalUrl: 'https://www.globusmedical.com/careers',
    postedAt: '12 hours ago',
    applicantCount: 18,
    h1bSponsorship: false,
    socialProof: 'Be an early applicant',
    matchScore: 72,
    atsType: 'workday',
  },
  {
    id: 'mock-8',
    title: 'Senior Data Engineer',
    company: 'Netflix',
    companyLogo: 'https://logo.clearbit.com/netflix.com',
    industry: 'Media & Entertainment',
    location: 'Los Gatos, CA',
    workModel: 'hybrid',
    jobType: 'fulltime',
    experienceLevel: 'senior',
    experienceYears: '5-8 years',
    salaryMin: 195000,
    salaryMax: 310000,
    description:
      'Build and maintain Netflix\'s data platform processing petabytes of streaming, engagement, and content data daily. Design real-time and batch data pipelines using Spark, Flink, and Iceberg. Drive data quality and governance initiatives.',
    applyUrl: 'https://jobs.lever.co/netflix/abc12345-def6-7890-ghij-klmnopqrstuv',
    companyPortalUrl: 'https://jobs.netflix.com',
    postedAt: '8 hours ago',
    applicantCount: 201,
    h1bSponsorship: true,
    socialProof: '4 school alumni work here',
    matchScore: 89,
    atsType: 'lever',
  },
  {
    id: 'mock-9',
    title: 'Product Manager, DeFi Protocols',
    company: 'Coinbase',
    companyLogo: 'https://logo.clearbit.com/coinbase.com',
    industry: 'Finance',
    location: 'Remote, US',
    workModel: 'remote',
    jobType: 'fulltime',
    experienceLevel: 'senior',
    experienceYears: '5-7 years',
    salaryMin: 175000,
    salaryMax: 260000,
    description:
      'Own the product vision and roadmap for Coinbase\'s DeFi protocol integrations. Work closely with blockchain engineers and designers to ship user-facing features that onboard the next 100M crypto users. Deep understanding of DeFi primitives required.',
    applyUrl: 'https://www.coinbase.com/careers/positions/5544332211',
    companyPortalUrl: 'https://www.coinbase.com/careers',
    postedAt: '4 hours ago',
    applicantCount: 63,
    h1bSponsorship: true,
    socialProof: '1 former colleague works here',
    matchScore: 78,
    atsType: 'greenhouse',
  },
  {
    id: 'mock-10',
    title: 'Machine Learning Engineer, Recommendations',
    company: 'Spotify',
    companyLogo: 'https://logo.clearbit.com/spotify.com',
    industry: 'Media & Entertainment',
    location: 'New York, NY',
    workModel: 'hybrid',
    jobType: 'fulltime',
    experienceLevel: 'mid',
    experienceYears: '3-5 years',
    salaryMin: 155000,
    salaryMax: 230000,
    description:
      'Develop and deploy machine learning models that power Spotify\'s personalized music and podcast recommendations. Work on large-scale retrieval, ranking, and exploration systems serving 600M+ users. Strong Python and TensorFlow/PyTorch experience required.',
    applyUrl: 'https://jobs.lever.co/spotify/f1e2d3c4-b5a6-7890-cdef-1234567890ab',
    companyPortalUrl: 'https://www.lifeatspotify.com',
    postedAt: '1 day ago',
    applicantCount: 178,
    h1bSponsorship: true,
    socialProof: '2 school alumni work here',
    matchScore: 86,
    atsType: 'lever',
  },
  {
    id: 'mock-11',
    title: 'Frontend Engineer, Design Systems',
    company: 'Figma',
    companyLogo: 'https://logo.clearbit.com/figma.com',
    industry: 'Software',
    location: 'San Francisco, CA',
    workModel: 'hybrid',
    jobType: 'fulltime',
    experienceLevel: 'mid',
    experienceYears: '3-5 years',
    salaryMin: 160000,
    salaryMax: 240000,
    description:
      'Build and maintain Figma\'s internal design system and component library. Create highly performant, accessible React components used across all Figma web surfaces. Work at the intersection of design and engineering to establish best practices.',
    applyUrl: 'https://app.greenhouse.io/boards/figma/jobs/4567890',
    companyPortalUrl: 'https://www.figma.com/careers',
    postedAt: '2 days ago',
    applicantCount: 245,
    h1bSponsorship: true,
    socialProof: '3 former colleagues work here',
    matchScore: 92,
    atsType: 'greenhouse',
  },
  {
    id: 'mock-12',
    title: 'Technical Program Manager, Cloud Infrastructure',
    company: 'Amazon',
    companyLogo: 'https://logo.clearbit.com/amazon.com',
    industry: 'Information Technology',
    location: 'Seattle, WA',
    workModel: 'onsite',
    jobType: 'fulltime',
    experienceLevel: 'senior',
    experienceYears: '6-10 years',
    salaryMin: 145000,
    salaryMax: 225000,
    description:
      'Drive cross-functional programs for AWS infrastructure services. Manage complex technical initiatives spanning multiple teams, define milestones, track risks, and communicate progress to VP-level stakeholders. Strong technical background required.',
    applyUrl: 'https://amazon.jobs/en/jobs/2345678/technical-program-manager-cloud-infrastructure',
    companyPortalUrl: 'https://amazon.jobs',
    postedAt: '5 hours ago',
    applicantCount: 312,
    h1bSponsorship: true,
    socialProof: '6 school alumni work here',
    matchScore: 76,
    atsType: 'custom',
  },
  {
    id: 'mock-13',
    title: 'Data Analyst, Growth',
    company: 'Notion',
    companyLogo: 'https://logo.clearbit.com/notion.so',
    industry: 'Software',
    location: 'San Francisco, CA',
    workModel: 'hybrid',
    jobType: 'fulltime',
    experienceLevel: 'entry',
    experienceYears: '1-3 years',
    salaryMin: 110000,
    salaryMax: 160000,
    description:
      'Analyze user acquisition, activation, and retention funnels to identify growth levers. Build dashboards and self-serve analytics tools for the growth team. Partner with product managers and engineers to design and evaluate experiments.',
    applyUrl: 'https://app.greenhouse.io/boards/notion/jobs/8901234',
    companyPortalUrl: 'https://www.notion.so/careers',
    postedAt: '30 minutes ago',
    applicantCount: 8,
    h1bSponsorship: true,
    socialProof: 'Be an early applicant',
    matchScore: 98,
    atsType: 'greenhouse',
  },
  {
    id: 'mock-14',
    title: 'Backend Engineer, Payments Platform',
    company: 'Square',
    companyLogo: 'https://logo.clearbit.com/squareup.com',
    industry: 'Finance',
    location: 'San Francisco, CA',
    workModel: 'remote',
    jobType: 'fulltime',
    experienceLevel: 'mid',
    experienceYears: '3-5 years',
    salaryMin: 145000,
    salaryMax: 215000,
    description:
      'Design and build scalable backend services powering Square\'s payment processing platform. Work with Java/Kotlin microservices, event-driven architectures, and distributed databases. Ensure PCI compliance and 99.99% uptime for critical payment flows.',
    applyUrl: 'https://jobs.smartrecruiters.com/Square/743999876543210-backend-engineer-payments-platform',
    companyPortalUrl: 'https://careers.squareup.com',
    postedAt: '10 hours ago',
    applicantCount: 87,
    h1bSponsorship: true,
    socialProof: '1 school alumni works here',
    matchScore: 83,
    atsType: 'smartrecruiters',
  },
  {
    id: 'mock-15',
    title: 'DevOps Engineer, Platform',
    company: 'Datadog',
    companyLogo: 'https://logo.clearbit.com/datadoghq.com',
    industry: 'Software',
    location: 'New York, NY',
    workModel: 'hybrid',
    jobType: 'fulltime',
    experienceLevel: 'mid',
    experienceYears: '3-6 years',
    salaryMin: 140000,
    salaryMax: 210000,
    description:
      'Build and maintain the internal developer platform that enables Datadog engineers to ship code confidently. Manage Kubernetes clusters, CI/CD pipelines, and infrastructure-as-code (Terraform). Improve deployment velocity and system observability.',
    applyUrl: 'https://app.greenhouse.io/boards/datadog/jobs/3456789',
    companyPortalUrl: 'https://careers.datadoghq.com',
    postedAt: '1 day ago',
    applicantCount: 64,
    h1bSponsorship: true,
    socialProof: '2 former colleagues work here',
    matchScore: 79,
    atsType: 'greenhouse',
  },
];
